name: Branch Protection

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black pylint
          
      - name: Run tests
        run: |
          pytest --cov=./ --cov-report=xml
          
      - name: Run linting
        run: |
          pylint **/*.py
          
      - name: Check formatting
        run: |
          black --check .
          
      - name: Check commit message format
        run: |
          git log -1 --pretty=%B | grep -E '^(feat|fix|docs|style|refactor|test|chore)(\([a-z-]+\))?: .+$' || exit 1
          
      - name: Check branch naming
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" && "${{ github.ref }}" != "refs/heads/develop" ]]; then
            if [[ ! "${{ github.ref }}" =~ ^refs/heads/(feature|hotfix|release)/ ]]; then
              echo "Branch name does not follow naming convention"
              exit 1
            fi
          fi 